package com.example.guest.wisecommute;

import com.example.guest.wisecommute.models.Stop;

/**
 * Created by Guest on 5/31/17.
 */

public class Constants {
    public static final String API_KEY = BuildConfig.Trimet_API_KEY;
    public static final String API_BASE_URL = "https://developer.trimet.org/ws/v2/arrivals?locIDs=";
    public static final String STOP_QUERY_ID = "locIDs"; //Example: "location"
    public static final String API_FORMAT = "json";
    public static final String API_KEY_QUERY_PARAMETER = "appID";

    public static final Stop[] greenToClackamasStops = {
            new Stop("Clackamas Town Center", "13132"),
            new Stop("SE Fuller Rd", "13130"),
            new Stop("SE Flavel St", "13129"),
            new Stop("Lents/SE Foster Rd", "13128"),
            new Stop("SE Holgate Blvd", "13127"),
            new Stop("SE Powell Blvd", "13128"),
            new Stop("SE Division St", "13125"),
            new Stop("SE Main St", "13124"),
            new Stop("Gateway/NE 99th Ave", "8347"),
            new Stop("NE 82nd Ave", "8346"),
            new Stop("NE 60th Ave", "8345"),
            new Stop("Hollywood/NE 42nd Ave", "8344"),
            new Stop("Lloyd Center/NE 11th Ave", "8343"),
            new Stop("NE 7th Ave", "8342"),
            new Stop("Convention Center", "8341"),
            new Stop("Rose Quarter", "8340"),
            new Stop("Union Station/NW 6th & Hoyt", "7763"),
            new Stop("NW 6th & Davis", "9299"),
            new Stop("NW 6th & Pine", "7787"),
            new Stop("Pioneer Courthouse/SW 6th Ave", "7777"),
            new Stop("SW 6th & Madison", "13123"),
            new Stop("PSU Urban Center/SW 6th & Montgomery", "7774"),
            new Stop("PSU South/SW 6th & College", "10293")
    };

    public static final Stop[] greenToCityCenterStops = {
            new Stop("Clackamas Town Center", "13132"),
            new Stop("SE Fuller Rd", "13133"),
            new Stop("SE Flavel St", "13134"),
            new Stop("Lents/SE Foster Rd", "13135"),
            new Stop("SE Holgate Blvd", "13136"),
            new Stop("SE Powell Blvd", "13137"),
            new Stop("SE Division St", "13138"),
            new Stop("SE Main St", "13139"),
            new Stop("Gateway/NE 99th Ave", "8370"),
            new Stop("NE 82nd Ave", "8371"),
            new Stop("NE 60th Ave", "8372"),
            new Stop("Hollywood/NE 42nd Ave", "8373"),
            new Stop("Lloyd Center/NE 11th Ave", "8374"),
            new Stop("NE 7th Ave", "8375"),
            new Stop("Convention Center", "8376"),
            new Stop("Rose Quarter", "8377"),
            new Stop("Union Station/NW 5th & Glisan", "7601"),
            new Stop("NW 5th & Couch", "9303"),
            new Stop("SW 5th & Oak", "7627"),
            new Stop("Pioneer Place/SW 5th Ave", "7646"),
            new Stop("City Hall/SW 5th & Jefferson", "7608"),
            new Stop("PSU Urban Center/SW 5th & Mill", "7618"),
            new Stop("PSU South/SW 5th & Jackson", "7606")
    };

    public static final Stop[] blueToHillsboroStops = {
            new Stop("Cleveland Ave", "8359"),
            new Stop("Gresham Central TC", "8360"),
            new Stop("Gresham City Hall", "8361"),
            new Stop("Civic Drive", "13449"),
            new Stop("Ruby Junction/E 197th Ave", "8362"),
            new Stop("Rockwood/E 188th Ave", "8363"),
            new Stop("E 181st Ave", "8364"),
            new Stop("E 172nd Ave", "8365"),
            new Stop("E 162nd Ave", "8366"),
            new Stop("E 148th Ave", "8367"),
            new Stop("E 122nd Ave", "8368"),
            new Stop("E 102nd Ave", "8369"),
            new Stop("Gateway/NE 99th Ave TC", "8370"),
            new Stop("NE 82nd Ave", "8371"),
            new Stop("NE 60th Ave", "8372"),
            new Stop("Hollywood/NE 42nd Ave TC", "8373"),
            new Stop("Lloyd Center/NE 11th Ave", "8374"),
            new Stop("NE 7th Ave", "8375"),
            new Stop("Convention Center", "8376"),
            new Stop("Rose Quarter TC", "8377"),
            new Stop("Old Town/Chinatown", "8378"),
            new Stop("Skidmore Fountain", "8379"),
            new Stop("Oak/SW 1st Ave", "8380"),
            new Stop("Morrison/SW 3rd Ave", "8381"),
            new Stop("Mall/SW 5th Ave", "8382"),
            new Stop("Pioneer Square North", "8383"),
            new Stop("Galleria/SW 10th Ave", "8384"),
            new Stop("Providence Park", "9757"),
            new Stop("Kings Hill/SW Salmon St", "9820"),
            new Stop("Goose Hollow/SW Jefferson St", "10117"),
            new Stop("Washington Park", "10121"),
            new Stop("Sunset TC", "9624"),
            new Stop("Beaverton TC", "9818"),
            new Stop("Beaverton Central", "9823"),
            new Stop("Millikan Way", "9825"),
            new Stop("Beaverton Creek", "9819"),
            new Stop("Merlo Rd/SW 158th Ave", "9827"),
            new Stop("Elmonica/SW 170th Ave", "9829"),
            new Stop("Willow Creek/SW 185th Ave", "9832"),
            new Stop("Quatama/NW 205th Ave", "9833"),
            new Stop("Orenco/NW 231st Ave", "9836"),
            new Stop("Hawthorn Farm", "9840"),
            new Stop("Fair Complex/Hillsboro Airport", "9837"),
            new Stop("Washington/SE 12th Ave", "9842"),
            new Stop("Tuality Hospital/SE 8th Ave", "9844"),
            new Stop("Hillsboro Central/SE 3rd Ave", "9845"),
            new Stop("Hatfield Government Center", "9848"),
            new Stop("Interstate/Rose Quarter", "11507"),
            new Stop("Providence Park", "9758")
    };

    public static final Stop[] blueToGreshamStops = {
            new Stop("Hatfield Government Center", "9848"),
            new Stop("Hillsboro Central/SE 3rd", "9846"),
            new Stop("Tuality Hospital/SE 8th Ave", "9843"),
            new Stop("Washington/SE 12th Ave", "9841"),
            new Stop("Fair Complex/Hillsboro Airport", "9838"),
            new Stop("Hawthorn Farm", "9839"),
            new Stop("Orenco/NW 231st Ave", "9835"),
            new Stop("Quatama/NW 205th Ave", "9834"),
            new Stop("Willow Creek/SW 185th Ave", "9831"),
            new Stop("Elmonica/SW 170th Ave", "9830"),
            new Stop("Merlo Rd/SW 158th Ave", "9828"),
            new Stop("Beaverton Creek", "9822"),
            new Stop("Millikan Way", "9826"),
            new Stop("Beaverton Central", "9824"),
            new Stop("Beaverton TC", "9821"),
            new Stop("Sunset TC", "9969"),
            new Stop("Washington Park", "10120"),
            new Stop("Goose Hollow/SW Jefferson St", "10118"),
            new Stop("Kings Hill/SW Salmon St", "9759"),
            new Stop("Providence Park", "9758"),
            new Stop("Library/SW 9th Ave", "8333"),
            new Stop("Pioneer Square South", "8334"),
            new Stop("Mall/SW 4th Ave", "8335"),
            new Stop("Yamhill District", "8336"),
            new Stop("Oak/SW 1st Ave", "8337"),
            new Stop("Skidmore Fountain", "8338"),
            new Stop("Old Town/Chinatown", "8339"),
            new Stop("Interstate/Rose Quarter", "11508"),
            new Stop("Rose Quarter TC", "8340"),
            new Stop("Convention Center", "8341"),
            new Stop("NE 7th Ave", "8342"),
            new Stop("Lloyd Center/NE 11th Ave", "8343"),
            new Stop("Hollywood/NE 42nd Ave", "8344"),
            new Stop("NE 60th Ave", "8345"),
            new Stop("NE 82nd Ave", "8346"),
            new Stop("Gateway/NE 99th Ave", "8347"),
            new Stop("E 102nd Ave", "8348"),
            new Stop("E 122nd Ave", "8349"),
            new Stop("E 148th Ave", "8350"),
            new Stop("E 162nd Ave", "8351"),
            new Stop("E 172nd Ave", "8352"),
            new Stop("E 181st Ave", "8353"),
            new Stop("Rockwood/E 188th Ave", "8354"),
            new Stop("Ruby Junction/E 197th Ave", "8355"),
            new Stop("Civic Drive", "13450"),
            new Stop("Gresham City Hall", "8356"),
            new Stop("Gresham Central TC", "8357"),
            new Stop("Cleveland Ave", "8359")
    };

    public static final Stop[] redToAirportStops = {
            new Stop("Beaverton TC", "9821"),
            new Stop("Sunset TC", "9969"),
            new Stop("Washington Park", "10120"),
            new Stop("Goose Hollow/SW Jefferson St", "10118"),
            new Stop("Kings Hill/SW Salmon St", "9759"),
            new Stop("Providence Park", "9758"),
            new Stop("Library/SW 9th Ave", "8333"),
            new Stop("Pioneer Square South", "8334"),
            new Stop("Mall/SW 4th Ave", "8335"),
            new Stop("Yamhill District", "8336"),
            new Stop("Oak/SW 1st Ave", "8337"),
            new Stop("Skidmore Fountain", "8338"),
            new Stop("Old Town/Chinatown", "8339"),
            new Stop("Rose Quarter TC", "8340"),
            new Stop("Convention Center", "8341"),
            new Stop("NE 7th Ave", "8342"),
            new Stop("Lloyd Center/NE 11th Ave", "8343"),
            new Stop("Hollywood/NE 42nd Ave", "8344"),
            new Stop("NE 60th Ave", "8345"),
            new Stop("NE 82nd Ave", "8346"),
            new Stop("Gateway/NE 99th Ave", "8347"),
            new Stop("Parkrose/Sumner TC", "10572"),
            new Stop("Cascades", "10574"),
            new Stop("Mt Hood Ave", "10576"),
            new Stop("Portland Int'l Airport", "10579")
    };

    public static final Stop[] redToBeavertonStops = {
            new Stop("", ""),
            new Stop("", ""),
            new Stop("", ""),
            new Stop("", ""),
            new Stop("", ""),
            new Stop("", ""),
            new Stop("", ""),
            new Stop("", ""),
            new Stop("", ""),
            new Stop("", ""),
            new Stop("", ""),
            new Stop("", ""),
            new Stop("", ""),
            new Stop("", ""),
            new Stop("", ""),
            new Stop("", ""),
            new Stop("", ""),
            new Stop("", ""),
            new Stop("", ""),
            new Stop("", ""),
            new Stop("", ""),
            new Stop("", ""),
    };

    public static final Stop[] yellowToExpoStops = {
            new Stop("", ""),
            new Stop("", ""),
            new Stop("", ""),
            new Stop("", ""),
            new Stop("", ""),
            new Stop("", ""),
            new Stop("", ""),
            new Stop("", ""),
            new Stop("", ""),
            new Stop("", ""),
            new Stop("", ""),
            new Stop("", ""),
            new Stop("", ""),
            new Stop("", ""),
            new Stop("", ""),
            new Stop("", ""),
            new Stop("", ""),
            new Stop("", ""),
            new Stop("", ""),
            new Stop("", ""),
            new Stop("", ""),
            new Stop("", ""),
    };

    public static final Stop[] yellowToCityCenterStops = {
            new Stop("", ""),
            new Stop("", ""),
            new Stop("", ""),
            new Stop("", ""),
            new Stop("", ""),
            new Stop("", ""),
            new Stop("", ""),
            new Stop("", ""),
            new Stop("", ""),
            new Stop("", ""),
            new Stop("", ""),
            new Stop("", ""),
            new Stop("", ""),
            new Stop("", ""),
            new Stop("", ""),
            new Stop("", ""),
            new Stop("", ""),
            new Stop("", ""),
            new Stop("", ""),
            new Stop("", ""),
            new Stop("", ""),
            new Stop("", ""),
    };

    public static final Stop[] orangeToCityCenterStops = {
            new Stop("", ""),
            new Stop("", ""),
            new Stop("", ""),
            new Stop("", ""),
            new Stop("", ""),
            new Stop("", ""),
            new Stop("", ""),
            new Stop("", ""),
            new Stop("", ""),
            new Stop("", ""),
            new Stop("", ""),
            new Stop("", ""),
            new Stop("", ""),
            new Stop("", ""),
            new Stop("", ""),
            new Stop("", ""),
            new Stop("", ""),
            new Stop("", ""),
            new Stop("", ""),
            new Stop("", ""),
            new Stop("", ""),
            new Stop("", ""),
    };

    public static final Stop[] orangeToMilwaukieStops = {
            new Stop("", ""),
            new Stop("", ""),
            new Stop("", ""),
            new Stop("", ""),
            new Stop("", ""),
            new Stop("", ""),
            new Stop("", ""),
            new Stop("", ""),
            new Stop("", ""),
            new Stop("", ""),
            new Stop("", ""),
            new Stop("", ""),
            new Stop("", ""),
            new Stop("", ""),
            new Stop("", ""),
            new Stop("", ""),
            new Stop("", ""),
            new Stop("", ""),
            new Stop("", ""),
            new Stop("", ""),
            new Stop("", ""),
            new Stop("", ""),
    };
}
